KristaShop.WebUI/Models/FooterViewModel.cs
namespace KristaShop.WebUI.Models {
    public class FooterViewModel {
        public string TermsOfUseUri { get; set; }
        public string FacebookLink { get; set; }
        public string VkLink { get; set; }
        public string InstagramLink { get; set; }
        public string YoutubeLink { get; set; }
        public string Contacts { get; set; }
        public string CatalogUri { get; set; }
    }
}

KristaShop.WebUI/Controllers/CatalogController.cs
using KristaShop.Business.DTOs;
using KristaShop.Business.Interfaces;
using KristaShop.Common.Enums;
using KristaShop.Common.Interfaces;
using KristaShop.Common.Models;
using KristaShop.WebUI.Infrastructure;
using KristaShop.WebUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KristaShop.Common.Extensions;
using KristaShop.DataReadOnly.DTOs;
using Serilog;
using ControllerBase = KristaShop.WebUI.Controllers.Common.ControllerBase;

namespace KristaShop.WebUI.Controllers {
    [Permission]
    [Authorize(AuthenticationSchemes = "FrontendScheme")]
    public class CatalogController : ControllerBase
    {
        private readonly INomenclatureService _nomenclatureService;
        private readonly ICatalogService _ctlgService;
        private readonly IDiscountService _discountService;
        private readonly ICategoryService _ctgrService;
        private readonly ILogger _logger;

        public CatalogController (INomenclatureService nomenclatureService, ICategoryService ctgrService,
            ICatalogService ctlgService, IDiscountService discountService, ILogger logger)
        {
            _nomenclatureService = nomenclatureService;
            _ctgrService = ctgrService;
            _ctlgService = ctlgService;
            _discountService = discountService;
            _logger = logger;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(NomFilterDTO filter, int page = 1)
        {
            const int modelInPage = 15;
            CatalogDTO catalog;
            if (!string.IsNullOrEmpty(filter.CatalogUri))
            {
                catalog = await _ctlgService.GetCatalogDetailsByUri(filter.CatalogUri, true, UserSession?.UserId ?? Guid.Empty);
                if (catalog == null) return BadRequest();

                filter.CatalogId = catalog?.Id;
            }
            else if(filter.CatalogId != null) {
                catalog = await _ctlgService.GetCatalogDetails(filter.CatalogId.Value, true, UserSession?.UserId ?? Guid.Empty);
                if (catalog == null) return BadRequest();

                filter.CatalogId = catalog?.Id;
                filter.CatalogUri = catalog?.Uri;
            } else {
                return BadRequest();
            }

            if (string.IsNullOrEmpty(filter.CatalogUri))
            {
                TempData["AlertResult"] = JsonConvert.SerializeObject(OperationResult.Failure(new List<string> { "У вас закрыт доступ к каталогам." }));
                return RedirectToAction(nameof(Index), "Home");
            }
            if (!catalog.IsOpen && UserSession == null)
            {
                TempData["AlertResult"] = JsonConvert.SerializeObject(OperationResult.Failure(new List<string> { "У вас закрыт доступ к каталогам." }));
                return RedirectToAction(nameof(Index), "Home");
            }

            filter.IsSet = catalog.IsSet;
            if (filter.OrderNew)
                filter.OrderColumn = filter.OrderColumn.Equals("OrderNewAsc") ? "OrderNewDesc" : "OrderNewAsc";
            else if (filter.OrderPrice)
                filter.OrderColumn = filter.OrderColumn.Equals("OrderPriceAsc") ? "OrderPriceDesc" : "OrderPriceAsc";

            if (string.IsNullOrEmpty(filter.OrderColumn))
                filter.OrderColumn = "";
            
            var discount = UserSession != null && !catalog.IsDisableDiscount ? await _discountService.GetDiscountAsync((Guid) filter.CatalogId, UserSession.UserId, Guid.Empty) : new DiscountDTO {DiscountPrice = 0, Type = DiscountType.None};

            var model = new NomFilterViewModel {
                Filter = filter,
                Catalog = catalog,
                Catalogs = await _ctlgService.GetCatalogsByUser(UserSession?.UserId),
                PageList = await _nomenclatureService.GetNomModelsByFilter(filter, page, modelInPage, UserSession?.UserId),
                Discount = discount,
                Page = page
            };
            return View(model);
        }

        public async Task<IActionResult> Search(NomFilterDTO filter)
        {
            var nomIds = await _nomenclatureService.GetNomIdsForSearch();
            ViewBag.Catalogs = new SelectList(await _ctlgService.GetCatalogsByUser(UserSession?.UserId), "Uri", "Name", filter.CatalogUri);
            return View(new SearchPanelViewModel { NomSearch = await _nomenclatureService.GetListsForSearchByNomIds(nomIds), NomFilter = filter });
        }

        [AllowAnonymous]
        public async Task<IActionResult> Products(NomFilterDTO filter,
            [FromServices] ISettingsManager settingsManager, [FromServices] IMenuContentService contentService)
        {
            List<SearchProductsViewModel> models = new List<SearchProductsViewModel>();
            if (!string.IsNullOrEmpty(filter.CatalogUri)) {
                var catalog = await _ctlgService.GetCatalogDetailsByUri(filter.CatalogUri);
                if (catalog == null) return BadRequest();

                filter.CatalogId = catalog.Id;
                var model = new SearchProductsViewModel {
                    Catalog = catalog,
                    NomModels = await _nomenclatureService.GetNomModelsByFilter(filter, 1, 1000, UserSession?.UserId),
                    Discount = UserSession != null && !catalog.IsDisableDiscount ? await _discountService.GetDiscountAsync((Guid)filter.CatalogId, UserSession.UserId, Guid.Empty) : new DiscountDTO { DiscountPrice = 0, Type = DiscountType.None }
                };
                models.Add(model);
            } else {
                var catalogs = await _ctlgService.GetCatalogsByUser(UserSession?.UserId);
                foreach (var catalog in catalogs) {
                    filter.CatalogId = catalog.Id;
                    var model = new SearchProductsViewModel {
                        Catalog = catalog,
                        NomModels = await _nomenclatureService.GetNomModelsByFilter(filter, 1, 1000, UserSession?.UserId),
                        Discount = UserSession != null && !catalog.IsDisableDiscount ? await _discountService.GetDiscountAsync((Guid)filter.CatalogId, UserSession.UserId, Guid.Empty) : new DiscountDTO { DiscountPrice = 0, Type = DiscountType.None }
                    };

                    if (model.NomModels.TotalItemCount > 0) {
                        models.Add(model);
                    }
                }
                filter.CatalogId = null;
                filter.CatalogUri = null;
            }

            if (filter.CategoryIds != null && filter.CategoryIds.Count == 1) {
                var category = await _ctgrService.GetCategoryDetails(filter.CategoryIds.First());
                ViewData["SearchTitle"] = category.Name;
                var description = await contentService.GetMenuContentByUrlAsync(settingsManager.Settings.OpenCatalogSearchDescription);
                ViewData["SearchDescription"] = description?.Body;
            }

            var searchCatalog = new SearchCatalogViewModel {
                Filter = filter,
                SearchProducts = models
            };

            ViewData["HasAccess"] = UserSession != null;
            return View(searchCatalog);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Product(Guid? nomId, string ctlgUri, int page = 1)
        {
            if (nomId.HasValue && !string.IsNullOrEmpty(ctlgUri))
            {
                var catalog = await _ctlgService.GetCatalogDetailsByUri(ctlgUri, true, UserSession?.UserId ?? Guid.Empty);
                if (catalog == null) return RedirectToAction("Model404", "Error");

                if (!catalog.IsOpen && UserSession == null)
                {
                    TempData["AlertResult"] = JsonConvert.SerializeObject(OperationResult.Failure(new List<string> { "У вас закрыт доступ к каталогу." }));
                    return RedirectToAction(nameof(Index), "Home");
                }

                var model = await _nomenclatureService.GetNomModelById(nomId.Value, ctlgUri, UserSession?.UserId);
                if (model == null) {
                    TempData["AlertResult"] = JsonConvert.SerializeObject(OperationResult.Failure(new List<string> { "Модель не найдена." }));
                    return RedirectToAction(nameof(Index), new {catalogUri = ctlgUri, page});
                }

                ViewBag.CatalogName = catalog.Name;
                ViewBag.IsOpenCatalog = catalog.IsOpen;
                model.CatalogId = catalog.Id;
                model.CatalogUri = ctlgUri;
               

                ViewData["CatalogPage"] = page;
                return View(model);
            }
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetColors(Guid nomenclatureId, Guid sizeId, Guid colorId,
            Guid catalogId, bool isSet) {
            try {
                if (nomenclatureId.IsEmpty() || sizeId.IsEmpty() || catalogId.IsEmpty())
                    return BadRequest();

                var catalog = await _ctlgService.GetCatalogDetails(catalogId);
                var isInStock = catalog.OrderForm == (int) OrderFormType.InStock;

                var colors = await _nomenclatureService.GetColorsBySizeAsync(catalogId, nomenclatureId, sizeId, isInStock);
                if (!colors.Any()) {
                    return BadRequest();
                }

                ProductDetailsDTO prices = null;
                if (UserSession != null) {
                    colorId = colors.Any(x => x.Id == colorId) ? colorId : colors.First().Id;
                    prices = await _nomenclatureService.GetProductDetails(nomenclatureId, sizeId, colorId, UserSession.UserId, catalogId, isSet);
                }

KristaShop.WebUI/Controllers/CategoryController.cs
using System.Threading.Tasks;
using KristaShop.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace KristaShop.WebUI.Controllers {
    public class CategoryController : Controller {
        private readonly ICategoryService _categoryService;
        private readonly IMenuContentService _contentService;
        private readonly ISettingsManager _settingsManager;

        public CategoryController(ICategoryService categoryService, IMenuContentService contentService,
            ISettingsManager settingsManager) {
            _categoryService = categoryService;
            _contentService = contentService;
            _settingsManager = settingsManager;
        }

        public async Task<IActionResult> Index() {
            var categoriesDescription = await _contentService.GetMenuContentByUrlAsync(_settingsManager.Settings.CategoriesDescription);
            if (categoriesDescription != null) {
                ViewData["Description"] = categoriesDescription.Body;
            }

            var categories = await _categoryService.GetCategories();
            return View(categories);
        }
    }
}

KristaShop.WebUI/Controllers/GalleryController.cs
using KristaShop.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace KristaShop.WebUI.Controllers
{
    public class GalleryController : Controller
    {
        private readonly IGalleryService _galleryService;
        private readonly IMenuContentService _menuContentService;
        private readonly string _url;

        public GalleryController(IGalleryService galleryService, IMenuContentService menuContentService)
        {
            _galleryService = galleryService;
            _menuContentService = menuContentService;
            _url = "/Gallery/Index";
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var content = await _menuContentService.GetMenuContentByUrlAsync(_url);
            ViewBag.Description = content?.Body;
            const int modelInPage = 12;
            var list = await _galleryService.GetPaginationGallerys(page, modelInPage);
            return View(list);
        }
    }
}

KristaShop.WebUI/Views/Shared/Components/Footer/Default.cshtml
@model FooterViewModel
@{
    var isAuthenticated = (bool)ViewData["IsAuthenticated"];
}
<div class="container-fluid p-0">
    <div class="row">
        <div class="col-lg-3 col-md-12 col-sm-12 text-md-center text-center text-lg-left text-footer mb-sm-0 mb-md-0 mb-lg-5">
            <h3 class="mb-2 text-header-18px text-uppercase text-footer footer-middle-section-header"><div style="height: 24px"></div></h3>
            <div class="pt-sm-0 pt-md-0 pt-lg-4  mb-4">
                <div class="my-2">
                    <a asp-controller="Category" asp-action="Index" class="link-basic-lighter text-uppercase">Категории</a>
                </div>
                <div class="my-2">
                    <a asp-controller="Catalog" asp-action="Index" asp-route-catalogUri="@Model.CatalogUri" class="link-basic-lighter text-uppercase">Каталоги</a>
                </div>
                <div class="my-2">
                    <a asp-controller="Contact" asp-action="Index" class="link-basic-lighter text-uppercase">Контакты</a>
                </div>
                <div class="my-2">
                    <a asp-controller="About" asp-action="Index" class="link-basic-lighter text-uppercase">О компании</a>
                </div>
                <div class="my-2">
                    <a asp-controller="Cooperation" asp-action="Index" class="link-basic-lighter text-uppercase">Условия сотрудничества</a>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-12 col-sm-12 text-center mb-sm-0 mb-md-0 mb-lg-5">
            <div class="row d-flex flex-row justify-content-center">
                <div class="col-md-12 col-lg-5 mb-4 text-left p-0 px-1">
                    <div class="footer-middle-section">
                        <div class="footer-middle-section-header text-footer header text-uppercase">Новости компаниии</div>
                        <div class="py-3">
                            <a asp-controller="InstaBlog" asp-action="Index" class="btn btn-basic btn-main-outline-grey-transparent text-footer font-weight-bold w-100">Instagram Blog</a>
                        </div>
                        <div class="py-3">
                            <a asp-controller="Gallery" asp-action="Index" class="btn btn-basic btn-main-outline-grey-transparent text-footer font-weight-bold w-100">Krista Stories</a>
                        </div>
                    </div>
                </div>

                <div class="col-lg-2 p-0 m-auto footer-middle-section-logo-wrapper">
                    <div class="footer-middle-section-logo">
                        <img src="/img/svg/krista-pic-transparent.gif" style="max-width: 100%"/>
                    </div>
                </div>

                <div class="col-md-12 col-lg-5 mb-4 p-0 text-right px-1">
                    <div class="footer-middle-section section-right">
                        <div class="footer-middle-section-header text-footer header text-uppercase">Напишите нам</div>
                        @if (isAuthenticated) {
                            <div class="py-3">
                                <a class="btn btn-basic btn-main-outline-grey-transparent text-footer font-weight-bold w-100" data-toggle="ajax-modal" data-target="#feedbackContactsModal">
                                    Связь с руководством
                                </a>
                            </div>
                            <div class="py-3">
                                <a class="btn btn-basic btn-main-outline-grey-transparent text-footer font-weight-bold w-100 px-0" data-toggle="ajax-modal" data-target="#feedbackModal">
                                    Книга жалоб и предложений
                                </a>
                            </div>
                        } else {
                            <div class="py-3">
                                <a class="btn btn-basic btn-main-outline-grey-transparent text-footer font-weight-bold w-100 px-0" data-toggle="ajax-modal" data-target="#feedbackModal">
                                    Обратная связь
                                </a>
                            </div>
                            <div class="py-3">
                                <a class="btn btn-basic btn-main-outline-grey-transparent text-footer font-weight-bold w-100 px-0" asp-action="Index" asp-controller="Contact">
                                    Контакты
                                </a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-12 col-sm-12 text-md-center text-center text-lg-right">
            <h3 class="mb-2 text-header-18px text-uppercase text-footer footer-middle-section-header">Социальные сети</h3>
            <div class="footer-social-networks-wrapper pt-sm-0 pt-md-0 pt-lg-3">
                <div class="text-left">
                    <div class="my-3 social-network">
                        <span class="logo icon icon-icomoon-instagram-outline icon-font-24px text-gradient px-2"></span>
                        <a href="@Model.InstagramLink" class="text link-basic-lighter text-uppercase">
                            Instagram подписаться
                        </a>
                    </div>
                    <div class="my-3 social-network">
                        <span class="logo icon icon-icomoon-facebook icon-font-24px text-gradient px-2"></span>
                        <a href="@Model.FacebookLink" class="text link-basic-lighter text-uppercase">
                            Facebook подписаться
                        </a>
                    </div>
                    <div class="my-3 social-network">
                        <span class="logo icon-icomoon-vk icon-font-24px text-gradient px-2" style="position: relative; bottom: -1px;"></span>
                        <a href="@Model.VkLink" class="text link-basic-lighter text-uppercase">
                            VK подписаться
                        </a>
                    </div>
                    <div class="my-3 social-network">
                        <span class="logo icon-icomoon-youtube icon-font-24px text-gradient px-2" style="position: relative; bottom: -1px;"></span>
                        <a href="@Model.YoutubeLink" class="text link-basic-lighter text-uppercase">
                            YouTube подписаться
                        </a>
                    </div>
                </div>
                @if (!string.IsNullOrEmpty(Model.Contacts)) {
                    <div class="phones-section">
                        <div class="phone-logos">
                            <span class="icon icon-font-24px icon-icomoon-watsapp-outline text-gradient ml-2 mr-2"></span>
                            <span class="icon icon-font-24px icon-icomoon-phone-outline text-gradient"></span>
                        </div>
                        <div class="phone-numbers">
                            @Html.RemoveTags(Model.Contacts)
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<!-- Copyright -->
<section class="copyright" style="flex-shrink: 0">
    <div class="container-fluid p-0">
        <div class="row">
            <div class="text text-lg-left text-md-center text-center col-md-3 col-sm-12">
                <div class="text-white">
                    &copy; 2020 KRISTA UNIQUE
                </div>
            </div>
            <div class="text text-center col-md-6 col-sm-12">
                <div class="text-white">
                    Все права на изображения принадлежат <span class="text-active">KRISTA UNIQUE</span>, любое использование запрещено.
                </div>
            </div>
            <div class="text text-lg-right text-md-center text-center col-md-3 col-sm-12">
                <div class="text-white">
                    <a href="@Model.TermsOfUseUri" class="text-white">Политика конфиденциальности сайта krista.fashion</a>
                </div>
            </div>
        </div>
    </div>
</section>