KristaShop.WebUI/Controllers/FaqController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KristaShop.Business.DTOs;
using KristaShop.Business.Interfaces;
using KristaShop.WebUI.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Serilog;

namespace KristaShop.WebUI.Controllers
{
    [Permission]
    [Authorize(AuthenticationSchemes = "FrontendScheme")]
    public class FaqController : Controller
    {
        private readonly IFaqService _faqService;
        private GlobalSettings _globalSettings;
        private readonly ILogger _logger;
        public FaqController(IFaqService faqService, IOptions<GlobalSettings> options, ILogger logger) 
        {
            _faqService = faqService;
            _globalSettings = options.Value;
            _logger = logger;
        }
        public async Task<IActionResult> Index(Guid faqId)
        {
            try
            {
                var faqs = _faqService.GetAllFaqs();
                var selectedSections = await _faqService.GetFaqSectionsAsync(faqId);
                var model = new FaqViewModel() { Faqs = faqs, SelectedFaqSections = selectedSections };
                model.SelectedSectionColorCode = await _faqService.GetFaqColorCode(faqId);
                return View(model);
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Failed to fetch faq info", ex.Message);
                return Json(new { success = false });
            }
        }

        public async Task<IActionResult> GetSections(Guid faqId)
        {
            try
            {
                var faqSections = await _faqService.GetFaqSectionsAsync(faqId);
                var faqSectionsColor = await _faqService.GetFaqColorCode(faqId);

                return Json(new { success=true, faqSections, faqSectionsColor });
            }
            catch (Exception ex) 
            {
                _logger.Error(ex, "Failed to fetch faq content", ex.Message);
                return Json(new { success = false, error = ex.Message });
            }
        }

        public async Task<IActionResult> GetSectionContent(Guid faqSectionId) 
        {
            try
            {
                var faqSectionContent = await _faqService.GetFaqSectionContentAsync(faqSectionId);

                return Json(new { success = true, faqSectionContent });
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Failed to fetch section content", ex.Message);
                return Json(new { success = false, error = ex.Message });
            }

        }
    }
}

KristaShop.WebUI/Controllers/ManagerController.cs
using KristaShop.Business.Interfaces;
using KristaShop.Common.Enums;
using KristaShop.Common.Interfaces;
using KristaShop.Common.Models;
using KristaShop.DataReadOnly.Interfaces;
using KristaShop.WebUI.Infrastructure;
using KristaShop.WebUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using KristaShop.Common.Extensions;
using KristaShop.Common.Helpers;
using KristaShop.WebUI.Utils.Extensions;
using Microsoft.AspNetCore.Http;
using Serilog;
using IUserService = KristaShop.Business.Interfaces.IUserService;

namespace KristaShop.WebUI.Controllers
{
    [Permission]
    [Authorize(AuthenticationSchemes = "FrontendScheme")]
    public class ManagerController : Controller
    {
        private readonly IUserService _userService;
        private readonly ICatalogService _catalogService;
        private readonly ILinkService _linkService;
        private readonly IAsupApiClient<UserUpdateViewModel> _apiClient;
        private readonly IMapper _mapper;
        private readonly ILogger _logger;

        public ManagerController
            (IUserService userService, ICatalogService catalogService,
            ILinkService linkService, IAsupApiClient<UserUpdateViewModel> apiClient,
            IMapper mapper, ILogger logger)
        {
            _userService = userService;
            _catalogService = catalogService;
            _linkService = linkService;
            _apiClient = apiClient;
            _mapper = mapper;
            _logger = logger;
        }

        public async Task<IActionResult> Index(UserParamsViewModel model, [FromServices] IFrontUserService userService)
        {
            var user = userService.Get();
            var clients = _userService.GetAllUsers(user);
            ViewBag.Catalogs = await _catalogService.GetCatalogs();
            ViewBag.NewUsers = new SelectList(clients.Where(x => x.Status == (int)UserStatus.Await).ToList(), "UserId", "ClientFullName", model.ParamUserId);
            ViewBag.AllUsers = new SelectList(clients, "UserId", "TitlePerson", model.ParamUserId);
            return View(model);
        }

        public async Task<IActionResult> GetUserParams(Guid? userId)
        {
            if (!userId.HasValue) {
                return BadRequest("Пользователь не выбран.");
            }

            var result = await _linkService.InsertLinkAuthAsync(userId.Value, AuthorizationLinkType.MultipleAccess, false);
            if (!result.IsSuccess) {
                _logger.Warning(result.Exception, "{message}. {@result}", result.ToString(), result);
                return BadRequest($"Произошла ошибка при получении ссылки для входа. {result.ReadableMessage}");
            }

            var ctlgIds = await _catalogService.GetNonVisUserCatalogs(userId.Value);
            bool isActiveUser = await _userService.IsActiveUserAsync(userId.Value);
            return Ok(new { link = result.Model, ctlgIds, isActiveUser });
        }

        public async Task<IActionResult> GetUserDetails(Guid userId, [FromServices] IDictionaryService dictionaryService) {
            if (userId == Guid.Empty) {
                TempData["AlertResult"] = JsonConvert.SerializeObject(OperationResult.Failure(new List<string> { "Клиент не выбран." }));
                return RedirectToAction(nameof(Index), new UserParamsViewModel());
            }

            var user = await _userService.GetUserAsync(userId);
            var model = _mapper.Map<UserUpdateViewModel>(user);
            model.Cities = new SelectList(dictionaryService.GetCities(), "Id", "Name");
            model.Statuses = new SelectList(UserStatusExtension.GetActivateStatuses(), "Key", "Value" );
            return PartialView("_UserDetails", model);
        }

        [HttpPost]
        public async Task<IActionResult> SetUserParams(UserParamsViewModel model) {
            try {
                if (!model.ParamUserId.IsEmpty()) {
                     await _catalogService.AddNonVisUserCatalogs(model.ParamUserId, model.NonVisCtlgIds);
                } else {
                    TempData["AlertResult"] = JsonConvert.SerializeObject(OperationResult.Failure());
                }
            } catch (Exception ex) {
                _logger.Error(ex, "Failed to set not visible catalogs for user {@model}. {message}", ex.Message, model);
                TempData["AlertResult"] = JsonConvert.SerializeObject(OperationResult.Failure());
            }

            return RedirectToAction(nameof(Index), new { model });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUserClient(UserUpdateViewModel model, [FromServices] IDictionaryService dictionaryService) {
            if (model.Id.IsEmpty()) {
                ModelState.TryAddModelError(string.Empty, "Пользователь не выбран");
            } else {
                model.Password = HashHelper.TransformPassword(model.Password);
                var result = await _apiClient.UpdateUserAsync(model);
                if (result.StatusCode < 400) {
                    return StatusCode(StatusCodes.Status206PartialContent, OperationResult.Success("Данные пользователя успешно обновлены"));
                }

                _logger.Error("Failed to update new user data {@model} {@result}", model, result);
                if (result.HasReadableMessage) {
                    ModelState.TryAddModelError(string.Empty, result.ReadableMessage);
                } else {
                    ModelState.TryAddModelErrors(OperationResult.Failure().Messages);
                }
            }

            model.Cities = new SelectList(dictionaryService.GetCities(), "Id", "Name");
            model.Statuses = new SelectList(UserStatusExtension.GetActivateStatuses(), "Key", "Value" );
            return PartialView("_UserDetails", model);
        } 
    }
}

KristaShop.WebUI/Views/Manager/Index.cshtml
@model UserParamsViewModel
@{
    ViewData["Title"] = "Панель клиента";
    var catalogs = ViewBag.Catalogs as List<CatalogDTO>;
}

<div class="container mt-3">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="card bg-active col-xl-4 col-lg-4 col-md-6 col-sm-12 p-0 text-white">
            <div class="card-body p-2">
                <form class="form-row" method="post" asp-action="SetUserParams">
                    <input hidden asp-for="ParamUserId" />
                    <div class="col-auto form-group">Контрагенты</div>
                    <div class="col-auto ml-auto form-group">
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="usersRadio1" name="usersRadio" class="custom-control-input manager-radio" value="true">
                            <label class="custom-control-label manager-radio-label" for="usersRadio1">Новые</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="usersRadio2" name="usersRadio" class="custom-control-input manager-radio" value="false">
                            <label class="custom-control-label manager-radio-label" for="usersRadio2">Все</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <a style="text-decoration:none; color:white;" asp-controller="Faq" asp-action="Index">Воронка</a>
                        </div>
                    </div>
                    <div class="users users-true col-12 form-group" hidden>
                        <select id="new-users-select" class="form-control user-selectbox mb-3 select2-dropdown" asp-items="ViewBag.NewUsers">
                            <option value="">Выберите контрагента</option>
                        </select>
                        <button type="button" id="change-user-btn" data-toggle="ajax-modal" data-target="#clientUpdateModal" class="btn btn-block bg-white text-active mdi mdi-pencil-circle-outline text-left mt-2" style="display: none;"> <b>Изменить</b></button>
                    </div>
                    <div class="users users-false col-12 form-group" hidden>
                        <select class="form-control user-selectbox select2-dropdown" asp-items="ViewBag.AllUsers">
                            <option value="">Выберите контрагента</option>
                        </select>
                    </div>
                    <div class="col-12 form-group">
                        <button type="button" class="btn btn-block bg-white text-active mdi mdi-phone-in-talk-outline text-left"> <b>Вызов</b></button>
                    </div>
                    <div class="col-12 form-group" style="display: none;">
                        <label>Ссылка для доступа к сайту</label>
                        <div class="input-group mb-2">
                            <div class="input-group-prepend bg-white rounded">
                                <div class="input-group-text"><i class="mdi mdi-link"></i></div>
                            </div>
                            <input type="text" class="form-control border-0" id="link" placeholder="Ссылка для доступа к сайту">
                            <div class="input-group-append bg-white rounded">
                                <a href="" class="btn btn-secondary" id="login-link"><span class="mdi mdi-login"></span></a>
                            </div>
                        </div>
                    </div>
                    <div id="catalogs-access-select" class="col-12" style="display: none;">
                        <div class="col-12 form-group">
                            <label>Закрыть доступ к каталогам</label>
                            @foreach (var catalog in catalogs) {
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input manager-checkbox" name="NonVisCtlgIds" id="customCheck-@catalog.Id" value="@catalog.Id">
                                    <label class="custom-control-label manager-checkbox-label" for="customCheck-@catalog.Id">@catalog.Name</label>
                                </div>
                            }
                        </div>
                        <div class="col-12 form-group m-0">
                            <button type="submit" class="btn btn-block bg-white text-active mdi mdi-check-circle-outline text-left"> <b>Применить</b></button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="clientUpdateModal" tabindex="-1" role="dialog" aria-labelledby="clientUpdateModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title">Клиент</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <ul class="nav nav-justified" role="tablist" hidden>
                    <li class="nav-item">
                        <a class="nav-link identity-link active" id="client-data-tab" data-toggle="tab" href="#client-data" role="tab" aria-controls="login" aria-selected="true" data-url="" data-base-url="@Url.Action("GetUserDetails", "Manager")">Клиент</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="client-data" role="tabpanel" aria-labelledby="client-data-tab">

                    </div>
                </div>
            </div>
            <div class="collapse rounded-0" id="collapseExample">
                <div class="modal-footer text-center text-white bg-active rounded-0 m-auto p-3">
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <environment include="Development">
        <link rel="stylesheet" href="~/css/select2-settings.css" asp-append-version="true" />
    </environment>
}

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <environment include="Development">
        <script src="~/js/manager/manager-page.js" asp-append-version="true" type="text/javascript"></script>
    </environment>
    <environment include="Production, Staging">
        <script src="~/js/min/manager-page.min.js" asp-append-version="true" type="text/javascript"></script>
    </environment>
}

KristaShop.WebUI/Views/Manager/_UserDetails.cshtml
@model UserUpdateViewModel
<div class="ajax-post-form">
    <form method="post" asp-action="UpdateUserClient">
        <div class="ajax-post-form-body">
            <input asp-for="Id" hidden />
            <input asp-for="Person" hidden/>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Login"></label>
                <input asp-for="Login" class="form-control rounded-0" placeholder="Логин" autofocus="" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <div class="input-group mb-2">
                    <div class="input-group-prepend bg-white rounded" title="Сгенерировать пароль" data-generate-password="#UserPassword">
                        <a class="btn btn-secondary"><span class="mdi mdi-lastpass"></span></a>
                    </div>
                    <input asp-for="Password" id="UserPassword" class="form-control rounded-0" placeholder="Пароль" />
                </div>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityId"></label>
                <select class="form-control rounded-0" asp-for="CityId" asp-items="Model.Cities">
                    <option value="">Другой город</option>
                </select>
                <span asp-validation-for="CityId" class="text-danger"></span>
            </div>
            @if (!string.IsNullOrEmpty(Model.NewCity)) {
                <div class="form-group">
                    <label asp-for="NewCity"></label>
                    <input asp-for="NewCity" class="form-control rounded-0" placeholder="Название города" />
                    <span asp-validation-for="NewCity" class="text-danger"></span>
                </div>
            }
            <div class="form-group">
                <label asp-for="MallAddress"></label>
                <input asp-for="MallAddress" class="form-control rounded-0" placeholder="Название торгового центра" />
                <span asp-validation-for="MallAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone"></label>
                <input asp-for="Phone" class="form-control rounded-0" placeholder="Номер телефона" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control rounded-0" placeholder="Электронная почта" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status"></label>
                <select class="form-control rounded-0" asp-for="Status" asp-items="Model.Statuses"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group mt-3">
            <button type="submit" class="btn btn-block btn-light rounded-0">Применить</button>
        </div>
    </form>
</div>